openapi: 3.0.0
info:
  title: Jobseeker-Test API
  description: For Assessment Full Stack Engineer 
  version: 1.0
servers:
  - url: http://localhost:8000/api
    description: for local server
  # - url: http://producation.app/api
  #   description: production server
paths:
  /users:
    get:
      summary: Returns a list of users.
      responses:
        '200': 
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string